-- ترحيل منيو مريديان الجديد (المطبخ + البار)
-- شغّله في Supabase SQL Editor. لو حصل أي خطأ، مفيش حاجة هتتنفّذ (transaction).

BEGIN;

-- 1) مسح المنيو القديم (الوصفات ثم المنتجات ثم التصنيفات)
DELETE FROM product_recipes;
DELETE FROM products;
DELETE FROM categories;

-- 2) التصنيفات الجديدة (بالترتيب + القسم)
INSERT INTO categories (name_ar, name_en, sort_order, department) VALUES
  ('الفطار', 'Breakfast', 1, 'restaurant'),
  ('الشوربة', 'Soup', 2, 'restaurant'),
  ('المقبلات والأطفال', 'Appetizers & Kids', 3, 'restaurant'),
  ('السلطات', 'Salad', 4, 'restaurant'),
  ('البيتزا', 'Pizza', 5, 'restaurant'),
  ('الباستا', 'Pasta', 6, 'restaurant'),
  ('البرجر', 'Burger', 7, 'restaurant'),
  ('الساندويتشات', 'Sandwich', 8, 'restaurant'),
  ('الأطباق الرئيسية', 'Main Course', 9, 'restaurant'),
  ('الركن الشرقي', 'Oriental Corner', 10, 'restaurant'),
  ('الإضافات', 'Add-ons', 11, 'restaurant'),
  ('حلويات', 'Desserts', 12, 'bar'),
  ('شاي', 'Tea', 13, 'bar'),
  ('كافيين', 'Caffeine', 14, 'bar'),
  ('أعشاب', 'Herbals', 15, 'bar'),
  ('قهوة', 'Coffee', 16, 'bar'),
  ('سحلب', 'Sahlab', 17, 'bar'),
  ('هوت شوكليت', 'Hot Chocolate', 18, 'bar'),
  ('آيس', 'Ice', 19, 'bar'),
  ('ميلك شيك', 'Milk Shake', 20, 'bar'),
  ('فرابيه', 'Frappe', 21, 'bar'),
  ('سموذي', 'Smoothie', 22, 'bar'),
  ('عصير طازة', 'Fresh Juice', 23, 'bar'),
  ('كوكتيل', 'Cocktail', 24, 'bar'),
  ('مشروبات غازية', 'Soft Drinks', 25, 'bar'),
  ('صودا', 'Souda', 26, 'bar');

-- 3) المنتجات الجديدة (مربوطة بالتصنيف بالاسم، الصور من Vercel)
INSERT INTO products (category_id, name_ar, name_en, price, image_url, is_available)
SELECT c.id, v.name_ar, v.name_en, v.price, v.img, true
FROM (VALUES
  ('الفطار', 'فطار شرقي', 'Oriental Breakfast', 120, '/menu-images/16688.jpg'),
  ('الفطار', 'فلاحي بارتي', 'Fellah-y Barty', 110, '/menu-images/ChatGPT_Image_May_24_2026_03_12_12_PM.png'),
  ('الفطار', 'أوملت / بيض عيون', 'Omelette / Fried Eggs', 100, '/menu-images/16688.jpg'),
  ('الفطار', 'كلوب ساندوتش', 'Toast Club Sandwich', 130, '/menu-images/505.jpg'),
  ('الشوربة', 'شوربة كريمة الدجاج بالبندق', 'Creamy Chicken Hazelnut Soup', 135, '/menu-images/RESIZED-cream-of-chicken-soup-9.jpg'),
  ('الشوربة', 'شوربة برافا (كريمة مشروم)', 'Cream Prava Soup', 120, '/menu-images/635.jpg'),
  ('الشوربة', 'شوربة سي فود', 'Zooba di Mare Soup', 270, '/menu-images/2849.jpg'),
  ('الشوربة', 'شوربة الخضار بالتورتيلا', 'Bean Tortilla Soup', 90, '/menu-images/111024.jpg'),
  ('المقبلات والأطفال', 'طاسة تشكن كرسبي جبنة', 'Cheese Crispy Chicken Skillet', 140, '/menu-images/112104.jpg'),
  ('المقبلات والأطفال', 'طاسة بطاطس جبنة', 'Cheese Potato Skillet', 100, '/menu-images/1600x450px_French_Fries_Overload.png'),
  ('المقبلات والأطفال', 'بطاطس كلاسيك', 'Classic Fries', 45, '/menu-images/34660.jpg'),
  ('المقبلات والأطفال', 'تشكن ناجتس', 'Chicken Nuggets', 100, '/menu-images/114331.jpg'),
  ('المقبلات والأطفال', 'صوابع موتزريلا ستيك', 'Mozzarella Sticks', 100, '/menu-images/112104.jpg'),
  ('المقبلات والأطفال', 'تشكن كساديا', 'Chicken Quesadilla', 175, '/menu-images/chicken-quesadillas-lead-668eeac0e860b.jpg'),
  ('المقبلات والأطفال', 'تشكن استربس', 'Chicken Strips', 120, '/menu-images/114331.jpg'),
  ('السلطات', 'جريك سلاد', 'Greek Salad', 90, '/menu-images/47169.jpg'),
  ('السلطات', 'تشكن سيزر', 'Chicken Caesar Salad', 140, '/menu-images/caesar-salad-crispy-chicken-744x866.jpg'),
  ('السلطات', 'تشكن فروت سلاد', 'Chicken Fruit Salad', 150, '/menu-images/66329.jpg'),
  ('السلطات', 'رانش كورن سلاد', 'Ranch Corn Salad', 130, '/menu-images/292.jpg'),
  ('البيتزا', 'تشيزي مارجريتا بيتزا', 'Cheesy Margarita Pizza', 110, '/menu-images/170.jpg'),
  ('البيتزا', 'سوبر سوبريم بيتزا', 'Super Supreme Pizza', 220, '/menu-images/642.jpg'),
  ('البيتزا', 'بيتزا تشكن ماك تشيز', 'Chicken Mac Cheese Pizza', 200, '/menu-images/652.jpg'),
  ('البيتزا', 'تشيكن ميلانو بيتزا', 'Chicken Milano Pizza', 190, '/menu-images/101409.jpg'),
  ('البيتزا', 'بيتزا تشكن باربكيو', 'Roast Chicken BBQ Pizza', 220, '/menu-images/1518_1_.jpg'),
  ('البيتزا', 'بيتزا تشيكن رانش', 'Chicken Ranch Pizza', 200, '/menu-images/2508.jpg'),
  ('البيتزا', 'ميكس سي فود بيتزا', 'Under the Sea Pizza', 320, '/menu-images/64790.jpg'),
  ('البيتزا', 'جمبري روكا رانش بيتزا', 'Shrimp Ranch Pizza', 280, '/menu-images/443197.jpg'),
  ('الباستا', 'بنا بالخضار', 'Vegetable Pasta', 90, '/menu-images/6903.jpg'),
  ('الباستا', 'الفريدو باستا', 'Alfredo Pasta', 190, '/menu-images/3106.jpg'),
  ('الباستا', 'نجرسكو باستا', 'Chicken Negresco Pasta', 210, '/menu-images/2149332826.jpg'),
  ('الباستا', 'تشكن دوريتوس رانش باستا', 'Chicken Doritos Ranch Pasta', 220, '/menu-images/6903.jpg'),
  ('الباستا', 'تشكن ماك تشيز الفورنو', 'Chicken Mac Cheese Al-Forno', 200, '/menu-images/2149332826.jpg'),
  ('الباستا', 'باستا جمبري ليمون', 'Lemon Garlic Shrimp Pasta', 250, '/menu-images/5869.jpg'),
  ('الباستا', 'اسبيشيال سي فود', 'Frutti Di Mari Pasta', 300, '/menu-images/1955.jpg'),
  ('البرجر', 'تشكن برجر', 'Chicken Burger', 150, '/menu-images/50895.jpg'),
  ('البرجر', 'تشكن فادج ساندوتش', 'Chicken Fudge Sandwich', 180, '/menu-images/3070.jpg'),
  ('البرجر', 'كلاسيك برجر', 'Classic Burger', 180, '/menu-images/19388.jpg'),
  ('البرجر', 'ميريديان برجر', 'Meridian Burger', 200, '/menu-images/9487.jpg'),
  ('البرجر', 'ديولكس برجر', 'Dulux Burger', 190, '/menu-images/2149637305.jpg'),
  ('الساندويتشات', 'تشيكن زنجر هالبينو', 'Chicken Zinger Jalapeno', 180, '/menu-images/30.jpg'),
  ('الساندويتشات', 'تشكن فاهيتا', 'Chicken Fajita Sandwich', 180, '/menu-images/5002.jpg'),
  ('الساندويتشات', 'تشيكن كريسبي', 'Chicken Crispy', 165, '/menu-images/505.jpg'),
  ('الساندويتشات', 'شيش طاووق رانش', 'Shish Tawook Ranch', 180, '/menu-images/19757.jpg'),
  ('الساندويتشات', 'ساندوتش كفتة', 'Kofta Sandwich', 150, '/menu-images/2182.jpg'),
  ('الساندويتشات', 'جمبري مقلي أو جريل', 'Fried or Grilled Shrimp', 225, '/menu-images/22044.jpg'),
  ('الأطباق الرئيسية', 'كلاسيك جريلد تشيكن', 'Classic Grilled Chicken', 260, '/menu-images/FAW-recipes-herb-and-lemon-roasted-chicken-hero-c4ba0aec56884683be482c47b1e1df11.jpg'),
  ('الأطباق الرئيسية', 'تشكن ماك تشيز', 'Chicken Mac Cheese', 290, '/menu-images/merlin_198330876_5fbaead6-4108-4ded-8921-7420146bf46d-superJumbo.jpg'),
  ('الأطباق الرئيسية', 'تشكن ميريديان', 'Chicken Meridian', 310, '/menu-images/2148189870.jpg'),
  ('الأطباق الرئيسية', 'تشكن كوردن بلو', 'Chicken Cordon Bleu', 310, '/menu-images/cordon-bleu.jpg'),
  ('الأطباق الرئيسية', 'تشكن تندوري', 'Tandoori Chicken', 300, '/menu-images/82614.jpg'),
  ('الأطباق الرئيسية', 'بيف فيليه', 'Beef Fillet', 450, '/menu-images/7643.jpg'),
  ('الأطباق الرئيسية', 'بيف فيلادلفيا', 'Beef Philadelphia', 430, '/menu-images/20111.jpg'),
  ('الأطباق الرئيسية', 'ريب آي', 'Ribeye', 450, '/menu-images/7643.jpg'),
  ('الأطباق الرئيسية', 'اسكالوب بانيه', 'Escalope', 380, '/menu-images/22840.jpg'),
  ('الأطباق الرئيسية', 'بيف استراجانوف', 'Beef Stroganoff', 400, '/menu-images/20111.jpg'),
  ('الأطباق الرئيسية', 'فاهيتا فراخ', 'Chicken Fajitas', 300, '/menu-images/chicken-fajitas-small-7.jpg'),
  ('الأطباق الرئيسية', 'فاهيتا لحم', 'Meat Fajitas', 430, '/menu-images/chicken-fajitas-small-7.jpg'),
  ('الأطباق الرئيسية', 'فاهيتا ميكس', 'Mix Fajita', 430, '/menu-images/chicken-fajitas-small-7.jpg'),
  ('الركن الشرقي', 'فراخ مسحب', 'Mashab Chicken', 300, '/menu-images/2774.jpg'),
  ('الركن الشرقي', 'كفتة', 'Kofta', 310, '/menu-images/2149358049.jpg'),
  ('الركن الشرقي', 'شيش طاووق', 'Shish Tawook', 300, '/menu-images/2148189870.jpg'),
  ('الركن الشرقي', 'ميكس شيش وكفتة', 'Mixed Shish & Kofta', 310, '/menu-images/20860.jpg'),
  ('الركن الشرقي', 'سمان مقلي أو مشوي', 'Fried or Grilled Quail', 320, '/menu-images/2774.jpg'),
  ('الركن الشرقي', 'ميريديان ميكس جريل', 'Meridian Mix Grill', 450, '/menu-images/3614.jpg'),
  ('الركن الشرقي', 'إضافة أرز أبيض', 'Add White Rice', 25, '/menu-images/95128_1_.jpg'),
  ('الركن الشرقي', 'إضافة أرز بسمتي', 'Add Basmati Rice', 30, '/menu-images/95128_1_.jpg'),
  ('الركن الشرقي', 'ملوخية', 'Molokhia', 30, '/menu-images/206654.jpg'),
  ('الركن الشرقي', 'بامية', 'Okra', 45, '/menu-images/8769.jpg'),
  ('الركن الشرقي', 'سلطة خضراء', 'Green Salad', 40, '/menu-images/47169.jpg'),
  ('الإضافات', 'إضافة تشكن', 'Add Chicken', 75, NULL),
  ('الإضافات', 'إضافة لحمة', 'Add Meat', 140, NULL),
  ('الإضافات', 'إضافة لحم مفروم', 'Add Minced Meat', 65, NULL),
  ('الإضافات', 'إضافة جمبري', 'Add Shrimp', 120, NULL),
  ('الإضافات', 'إضافة ميكس تشيز', 'Add Mixed Cheese', 55, NULL),
  ('الإضافات', 'إضافة جبنة موتزريلا', 'Add Mozzarella', 30, NULL),
  ('الإضافات', 'إضافة مشروم', 'Add Mushrooms', 20, NULL),
  ('الإضافات', 'إضافة خضار', 'Add Vegetables', 20, NULL),
  ('الإضافات', 'إضافة صوص سخن', 'Add Hot Sauce', 15, NULL),
  ('الإضافات', 'إضافة صوص بارد', 'Add Cold Sauce', 15, NULL),
  ('الإضافات', 'إضافة صوص شيدر', 'Add Cheddar Sauce', 25, NULL),
  ('الإضافات', 'إضافة فلفل هالبينو', 'Add Jalapeños', 10, NULL),
  ('الإضافات', 'إضافة أطراف محشو جبنة', 'Add Stuffed Crust', 65, NULL),
  ('حلويات', 'ام علي مكسرات', 'Om Ali Nuts', 100, NULL),
  ('حلويات', 'ام علي بلح ومكسرات', 'Om Ali Dates & Nuts', 110, NULL),
  ('حلويات', 'ام علي نوتيلا', 'Om Ali Nutella', 110, NULL),
  ('حلويات', 'ام علي فواكه', 'Om Ali Fruits', 145, NULL),
  ('حلويات', 'سلطة فواكه', 'Fruit Salad', 120, NULL),
  ('حلويات', 'زبادي فواكه قطع', 'Fruit Yogurt Cubes', 130, NULL),
  ('حلويات', 'توتي فروتي', 'Totty Fruity', 130, NULL),
  ('حلويات', 'صنداي سبيشيال (نوتيلا/اوريو/لوتس/بلوبيري/بستاشيو)', 'Sunday Especial', 125, NULL),
  ('حلويات', 'صنداي كلاسيك (كريمة+صوص+مكسرات)', 'Sunday Classic', 110, NULL),
  ('حلويات', 'ايس كريم كلاسيك (3 سكوب)', 'IceCream Classic', 95, NULL),
  ('حلويات', 'وافل شوكولاتة', 'Chocolate Waffle', 95, NULL),
  ('حلويات', 'وافل اوريو', 'Oreo Waffle', 110, NULL),
  ('حلويات', 'وافل نوتيلا', 'Nutella Waffle', 100, NULL),
  ('حلويات', 'وافل فور سيزون', 'Four Seasons Waffle', 110, NULL),
  ('حلويات', 'وافل نوتيلا و لوتس', 'Nutella & Lotus Waffle', 110, NULL),
  ('حلويات', 'وافل لوتس', 'Lotus Waffle', 100, NULL),
  ('حلويات', 'مولتن كيك', 'Molten Cake', 110, NULL),
  ('حلويات', 'كيك شوكولاتة', 'Chocolate Cake', 100, NULL),
  ('حلويات', 'تشيز كيك', 'Cheese Cake', 100, NULL),
  ('حلويات', 'ميجا براونيز', 'Mega Brownies', 100, NULL),
  ('حلويات', 'سان سيباستيان', 'San Sebastian', 100, NULL),
  ('حلويات', 'ريد فيلفيت', 'Red Velvet', 100, NULL),
  ('شاي', 'شاي', 'Tea', 30, NULL),
  ('شاي', 'شاي نعناع / قرنفل', 'Tea Mint / Clove', 35, NULL),
  ('شاي', 'شاي أخضر', 'Green Tea', 35, NULL),
  ('شاي', 'براد شاي صغير / كبير', 'Tea Pot Small / Large', 40, NULL),
  ('شاي', 'شاي بالحليب', 'Milk Tea', 60, NULL),
  ('شاي', 'شاي كرك', 'Karak Tea', 55, NULL),
  ('كافيين', 'اسبريسو سنجل / دبل', 'Espresso Single / Double', 40, NULL),
  ('كافيين', 'هابي اسبريسو', 'Happy Espresso', 75, NULL),
  ('كافيين', 'ميكاتو', 'Macchiato', 65, NULL),
  ('كافيين', 'كورتادو', 'Cortado', 65, NULL),
  ('كافيين', 'فلات وايت', 'Flat White', 80, NULL),
  ('كافيين', 'كابتشينو كلاسيك / فلفر', 'Cappuccino Classic / Flavor', 80, NULL),
  ('كافيين', 'لاتيه', 'Latte', 80, NULL),
  ('كافيين', 'سبانش لاتيه', 'Spanish Latte', 95, NULL),
  ('أعشاب', 'كوندريلا (جنزبيل عسل ليمون)', 'Condrella (Ginger Lime Honey)', 45, NULL),
  ('أعشاب', 'أعشاب (نعناع ينسون كركديه)', 'Herbals (Mint Anise Hibiscus)', 35, NULL),
  ('أعشاب', 'هوت سيدر', 'Hot Cider', 65, NULL),
  ('أعشاب', 'هوت سينامون', 'Hot Cinnamon', 70, NULL),
  ('قهوة', 'قهوة تركي سنجل / دبل', 'Turkish Coffee Single / Double', 35, NULL),
  ('قهوة', 'قهوة فرنساوي', 'French Coffee', 45, NULL),
  ('قهوة', 'قهوة بندق', 'Hazelnut Coffee', 50, NULL),
  ('سحلب', 'سحلب مكسرات', 'Sahlab Nuts', 80, NULL),
  ('سحلب', 'سحلب نوتيلا / لوتس', 'Sahlab Nutella / Lotus', 95, NULL),
  ('سحلب', 'سحلب اوريو', 'Sahlab Oreo', 95, NULL),
  ('سحلب', 'سحلب فواكه', 'Sahlab Fruit', 125, NULL),
  ('هوت شوكليت', 'هوت شوكليت كلاسيك', 'Hot Chocolate Classic', 70, NULL),
  ('هوت شوكليت', 'هوت شوكليت نوتيلا', 'Hot Chocolate Nutella', 80, NULL),
  ('هوت شوكليت', 'هوت شوكليت لوتس', 'Hot Chocolate Lotus', 80, NULL),
  ('آيس', 'ايس امريكانو', 'Ice Americano', 70, NULL),
  ('آيس', 'ايس كابتشينو', 'Ice Cappuccino', 85, NULL),
  ('آيس', 'ايس لاتيه', 'Ice Latte', 80, NULL),
  ('آيس', 'ايس سبانش لاتيه', 'Ice Spanish Latte', 90, NULL),
  ('آيس', 'ايس ميكاتو', 'Ice Macchiato', 85, NULL),
  ('آيس', 'ايس موكا', 'Ice Mocha', 95, NULL),
  ('آيس', 'ايس نوتيلا', 'Ice Nutella', 90, NULL),
  ('آيس', 'ايس كراميل', 'Ice Caramel', 85, NULL),
  ('آيس', 'ايس تشوكليت', 'Ice Chocolate', 85, NULL),
  ('ميلك شيك', 'ميلك شيك فانيليا', 'Vanilla Milk Shake', 85, NULL),
  ('ميلك شيك', 'ميلك شيك تشوكلت', 'Chocolate Milk Shake', 85, NULL),
  ('ميلك شيك', 'ميلك شيك فراولة', 'Strawberry Milk Shake', 85, NULL),
  ('ميلك شيك', 'ميلك شيك مانجو', 'Mango Milk Shake', 85, NULL),
  ('ميلك شيك', 'ميلك شيك كراميل', 'Caramel Milk Shake', 95, NULL),
  ('ميلك شيك', 'ميلك شيك بلوبيري', 'Blueberry Milk Shake', 95, NULL),
  ('ميلك شيك', 'ميلك شيك اوريو', 'Oreo Milk Shake', 95, NULL),
  ('ميلك شيك', 'ميلك تشيز (نوتيلا/لوتس/بيستاشيو/كيندر)', 'Milk Cheese', 100, NULL),
  ('فرابيه', 'فرابيه كوفي', 'Frappe Coffee', 85, NULL),
  ('فرابيه', 'فرابيه كراميل', 'Frappe Caramel', 100, NULL),
  ('فرابيه', 'فرابيه فانيليا', 'Frappe Vanilla', 85, NULL),
  ('فرابيه', 'فرابيه تشوكلت', 'Frappe Chocolate', 85, NULL),
  ('فرابيه', 'فرابيه نوتيلا', 'Frappe Nutella', 100, NULL),
  ('فرابيه', 'فرابيه لوتس', 'Frappe Lotus', 100, NULL),
  ('سموذي', 'ليمون نعناع', 'Lemon Mint', 90, NULL),
  ('سموذي', 'اناناس', 'Pineapple', 95, NULL),
  ('سموذي', 'تروبيكا', 'Tropica', 95, NULL),
  ('سموذي', 'بلو اوشن', 'Blue Ocean', 95, NULL),
  ('سموذي', 'باشون فروت', 'Passion Fruit', 90, NULL),
  ('سموذي', 'كيوي', 'Kiwi', 100, NULL),
  ('سموذي', 'مانجو', 'Mango', 95, NULL),
  ('سموذي', 'فراولة', 'Strawberry', 85, NULL),
  ('سموذي', 'بلوبيري', 'Blueberry', 95, NULL),
  ('سموذي', 'ميكس بيري', 'Mix Berries', 85, NULL),
  ('سموذي', 'بطيخ', 'Watermelon', 90, NULL),
  ('سموذي', 'خوخ', 'Peach', 90, NULL),
  ('سموذي', 'تفاح أخضر', 'Green Apple', 90, NULL),
  ('عصير طازة', 'برتقال', 'Orange', 85, NULL),
  ('عصير طازة', 'رمان', 'Pomegranate', 80, NULL),
  ('عصير طازة', 'ليمون', 'Lemon', 80, NULL),
  ('عصير طازة', 'ليمون نعناع', 'Lemon Mint', 85, NULL),
  ('عصير طازة', 'بلح', 'Dates', 90, NULL),
  ('عصير طازة', 'زبادي', 'Yogurt', 80, NULL),
  ('عصير طازة', 'افوكادو', 'Avocado', 115, NULL),
  ('عصير طازة', 'مانجو', 'Mango', 90, NULL),
  ('عصير طازة', 'فراولة', 'Strawberry', 80, NULL),
  ('عصير طازة', 'جوافة', 'Guava', 80, NULL),
  ('عصير طازة', 'اناناس', 'Pineapple', 90, NULL),
  ('عصير طازة', 'كيوي', 'Kiwi', 95, NULL),
  ('عصير طازة', 'موز', 'Banana', 80, NULL),
  ('عصير طازة', 'بطيخ', 'Watermelon', 85, NULL),
  ('كوكتيل', 'فلوريدا (مانجو فراولة جوافة)', 'Florida', 95, NULL),
  ('كوكتيل', 'روج (مانجو فراولة موز)', 'Roug', 95, NULL),
  ('كوكتيل', 'جرين لايت (جوافة ليمون نعناع)', 'Green Light', 90, NULL),
  ('كوكتيل', 'ماجيك جرين (كيوي مانجو)', 'Magic Green', 95, NULL),
  ('كوكتيل', 'مانجو بيتش (مانجو خوخ باشون)', 'Mango Peach', 95, NULL),
  ('كوكتيل', 'هوريكان (مانجو افوكادو بلوبيري)', 'Hurricane', 125, NULL),
  ('كوكتيل', 'إنرجي (افوكادو بلح مكسرات)', 'Energy', 125, NULL),
  ('كوكتيل', 'باور (افوكادو مانجو مكسرات)', 'Power', 125, NULL),
  ('كوكتيل', 'زبادي فواكه', 'Fruit Yogurt', 110, NULL),
  ('مشروبات غازية', 'مياه معدنية', 'Water', 15, NULL),
  ('مشروبات غازية', 'مشروب غازي (بيبسي/سفن/ميرندا)', 'Soft Drinks', 50, NULL),
  ('مشروبات غازية', 'فيروز', 'Fayrouz', 60, NULL),
  ('مشروبات غازية', 'بيريل', 'Birell', 60, NULL),
  ('مشروبات غازية', 'ريد بول', 'Red Bull', 95, NULL),
  ('صودا', 'موهيتو كلاسيك', 'Mojito Classic', 85, NULL),
  ('صودا', 'موهيتو فروت', 'Mojito Fruit', 95, NULL),
  ('صودا', 'موهيتو ريد بول', 'Mojito Red Bull', 125, NULL),
  ('صودا', 'ريد بول ميكس', 'Red Bull Mix', 145, NULL),
  ('صودا', 'شيري كولا', 'Cherry Cola', 85, NULL),
  ('صودا', 'صن شاين', 'SunShine', 85, NULL),
  ('صودا', 'صودا بلوبيري', 'Souda Blueberry', 90, NULL),
  ('صودا', 'صودا فراولة', 'Souda Strawberry', 90, NULL),
  ('صودا', 'صودا كيوي', 'Souda Kiwi', 90, NULL)
) AS v(cat_ar, name_ar, name_en, price, img)
JOIN categories c ON c.name_ar = v.cat_ar;

COMMIT;
